Module7 task3
htmlacademy-nodejs/505149-typoteka-3 pull request #21
Opened 2021-08-24 15:48 UTC by deniolp

2021-08-27 01:12 UTC, Krabaton requested changes

2021-08-27 01:12 UTC, Krabaton commented on src/constants.js
> +module.exports.MULTER_UPLOAD_DIR = `../upload/img/`;
Не надо использовать относительный путь

2021-08-27 01:12 UTC, Krabaton commented on src/express/routes/search-routes.js
> +        message: `Ничего не найдено`,
Повтор кода пошел. Может лучше в константы собщения вынести?

2021-08-27 01:12 UTC, Krabaton commented on src/service/api/user.js
> +  route.post(`/auth`, async (req, res) => {
Валидации на то, что придут поля {email, password} нет?

2021-08-28 07:30 UTC, deniolp commented on src/constants.js
> +module.exports.MULTER_UPLOAD_DIR = `../upload/img/`;
Понял, исправил)

2021-08-28 07:39 UTC, deniolp commented on src/express/routes/search-routes.js
> +        message: `Ничего не найдено`,
Сделал перечисление в константах

2021-08-28 07:46 UTC, deniolp commented on src/service/api/user.js
> +  route.post(`/auth`, async (req, res) => {
Я думал, что на фронте достаточно required. Но сейчас добавил проверку

2021-08-30 06:59 UTC, merged